package com.mposluszny.lolesportsapp.core.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hsqldb.lib.StringUtil;

import com.mposluszny.lolesportsapp.core.dao.GenericDAO;
import com.mposluszny.lolesportsapp.core.dao.PlayerDao;
import com.mposluszny.lolesportsapp.core.model.Player;

public class PlayerDaoImpl extends GenericDAO<Player> implements PlayerDao {
	
	public PlayerDaoImpl (Connection connection, Statement statement, PreparedStatement preparedStatement) {
				
		super(connection, statement, preparedStatement, "Player");
		
		ResultSet rs;
		
		try {
			
			rs = connection.getMetaData().getTables(null, null, null, null);
			
			boolean tableExists = false;
			
			while (rs.next()) {
				String name = rs.getString("TABLE_NAME");
				if (tableName.equalsIgnoreCase(name)) {
					tableExists = true;
					break;
				}
			}
			
			if (!tableExists) {
				preparedStatement =
					connection.prepareStatement("CREATE TABLE Player (idPlayer BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,"
																+ " name VARCHAR (30) NOT NULL,"
																+ " surname VARCHAR(50) NOT NULL,"
																+ " ign VARCHAR(30) NOT NULL,"
																+ " role VARCHAR(10) NOT NULL,"
																+ " idTeam BIGINT FOREIGN KEY REFERENCES Team(idTeam),"
																+ " isRetired BOOLEAN DEFAULT FALSE);");
				preparedStatement.execute();
			}
			
		} catch (SQLException e) {

			e.printStackTrace();
		}
		
	}
	
	@Override
	public List<Player> getAllPlayers() {
		
		try {
			
			statement = connection.createStatement();
			ResultSet rs = statement.executeQuery("SELECT * FROM Player;");
			List<Player> players = new ArrayList<Player>();
			
			while (rs.next()) {
				
				Player player = new Player(rs.getString("name"),
										   rs.getString("surname"),
										   rs.getString("ign"),
										   rs.getString("role"),
										   rs.getLong("idTeam"),
										   rs.getBoolean("isRetired"));
				player.setIdPlayer(rs.getLong("idPlayer"));
				players.add(player);
			}
			
			return players;
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		
		return null;
	}

	@Override
	public Player getPlayerById(long idPlayer) {
		
		try {
			
			statement = connection.createStatement();
			ResultSet rs = statement.executeQuery("SELECT * FROM Player WHERE idPlayer=" + idPlayer + ";");
		
			if (rs.next()) {
				
				Player player = new Player(rs.getString("name"),
										   rs.getString("surname"),
										   rs.getString("ign"),
										   rs.getString("role"),
										   rs.getLong("idTeam"),
										   rs.getBoolean("isRetired"));
				player.setIdPlayer(rs.getLong("idPlayer"));
				
				return player;
			}
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		
		return null;
	}

	@Override
	public Player getPlayerByIgn(String ign) {

		try {
			
			statement = connection.createStatement();
			ResultSet rs = statement.executeQuery("SELECT * FROM Player WHERE ign=\'" + ign + "\';");

			if (rs.next()) {
				//Long idTeam = rs.getLong("idTeam");
				Player player = new Player(rs.getString("name"),
										   rs.getString("surname"),
										   rs.getString("ign"),
										   rs.getString("role"),
										   rs.getLong("idTeam"),
										   rs.getBoolean("isRetired"));
				player.setIdPlayer(rs.getLong("idPlayer"));
				
				return player;
			}
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}
		
		return null;
	}
	
	@Override
	public void updatePlayer(Player player) {
		
		try {
			
			preparedStatement = connection.prepareStatement(
											"UPDATE Player SET name=\'" + player.getName() + "\'" +
															  ", surname=\'" + player.getSurname() + "\'" +
															  ", ign=\'" + player.getIgn() + "\'" +
															  ", role=\'" + player.getRole() + "\'" +
															  ", idTeam=" + player.getTeam().getIdTeam() +
															  ", isRetired=" + player.isRetired() +
															  " WHERE idPlayer=" + player.getIdPlayer() + ";");
			preparedStatement.execute();
			
		} catch (SQLException e) {
			
			e.printStackTrace();
		}

	}

	@Override
	public void addPlayer(Player player) {
		
		String query;
		
		try {
			
			String getIdTeamQuery = "SELECT idTeam FROM Team WHERE name=\'" + player.getTeam().getName() + "\'";
			
			if (!StringUtil.isEmpty(player.getTeam().getName())) {
				
				query = String.format("INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED)"
						+ " VALUES (\'%s\', \'%s\', \'%s\', \'%s\', (%s), %b);", player.getName(), player.getSurname(),
						player.getIgn(), player.getRole(), getIdTeamQuery, player.isRetired());
			}
			
			else {
				
				query = String.format("INSERT INTO Player (NAME, SURNAME, IGN, ROLE, IDTEAM, ISRETIRED)"
						+ " VALUES (\'%s\', \'%s\', \'%s\', \'%s\', %s, %b);", player.getName(), player.getSurname(),
						player.getIgn(), player.getRole(), (player.getTeam().getIdTeam() == 0L ? "null" : String.valueOf(player.getTeam().getIdTeam())), player.isRetired());
			}
			
			preparedStatement = 
					connection.prepareStatement(query);
			preparedStatement.execute();
			
		} catch (SQLException e) {

			e.printStackTrace();
		}
		
	}
	

	@Override
	public boolean deletePlayer(Player player) {
		
		try {
						
			if (!StringUtil.isEmpty(player.getIgn())) {
				
				preparedStatement = connection.prepareStatement("DELETE FROM Player WHERE ign=\'" + player.getIgn() + "\';");
			}
			
			else if (!StringUtil.isEmpty(player.getName()) && !StringUtil.isEmpty(player.getSurname())) {
				
				preparedStatement = connection.prepareStatement("DELETE FROM Player WHERE name=\'" + player.getName() + "\' AND surname=\'" + player.getSurname() + "\';");
			}
			
			else if (player.getIdPlayer() != 0L) {
				
				preparedStatement = connection.prepareStatement("DELETE FROM Player WHERE idPlayer=" + player.getIdPlayer() + ";");
			}
			
			else {
				
				throw new SQLException("Blad w wywolywaniu metody deletePlayer");
			}
			
			preparedStatement.execute();
			return true;
			
		} catch (SQLException e) {

			e.printStackTrace();
		}
		
		return false;
		
	}

}